@api = http://localhost:3000
@path = {{api}}/api/post
@token = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMkBnbWFpbC5jb20iLCJuYW1lIjoiVXNlciAyIiwiZXhwIjoxNzI0MTQ2NDM0fQ.AeUglzzPpW-D6MNDJEe2Utp_omyExe2Egxrbd_TmCxM
###
GET  {{api}}/hello
Content-Type: application/json

###
GET  {{path}}/all
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET  {{path}}/all/1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET  {{path}}/user
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET  {{path}}/user/1
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST  {{path}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "msg": "is message test",
  "title": "not have title",
  "userId": 3333
}
