@api = http://localhost:3000
@path = {{api}}/api/product
@token = eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyMkBnbWFpbC5jb20iLCJuYW1lIjoiVXNlciAyIiwiZXhwIjoxNzI0MTQ2NDM0fQ.AeUglzzPpW-D6MNDJEe2Utp_omyExe2Egxrbd_TmCxM
###
GET  {{api}}/hello
Content-Type: application/json

###
GET  {{path}}
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET  {{path}}/10
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST  {{path}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "not have title",
  "price": {{$randomInt 1 23}},
  "qty":  {{$randomInt}},
  "exp": "{{$isoTimestamp}}"
}

###

PUT  {{path}}/7
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "update data",
  "price": {{$random.integer(0,100)}},
  "qty":  {{$randomInt}},
  "exp": "{{$isoTimestamp}}"
}

###
DELETE  {{path}}/6
Content-Type: application/json
Authorization: Bearer {{token}}
